### ISSUE TITLE
.NET Core Docker

### ISSUE THREAD

**Issue by jjradke** [LorenData/ECGridOS_API#4]
Good morning,

I am converting our older code to run all my EDI logic in .NET Core 2.0 microservices running in Docker in Linux.  Do you have any examples/samples of using your soap API's in .NET Core 2.0 application?

Thanks,

Jim

**Comment by GregKolinski** [comment]
Hello Jim,

Yes, there is an example project in the code tab called [ECGridOS .Net Core Examples](https://github.com/LorenData/ECGridOS_API/tree/master/ECGridOS%20API%20.NET%20Core%20Examples/ECGridOS_CORE_Examples). 

You can use the ServiceModel from the example and build out the example Client or you can create your own.  We used the ServiceModel Metadata Utility Tool (Svcutil.exe) to create the one in the example, instructions can be found [here](https://docs.microsoft.com/en-us/dotnet/framework/wcf/servicemodel-metadata-utility-tool-svcutil-exe). 

It basically takes the WSDL and builds out all the class objects like in the full .NET "Add Service Reference".  There is also a[ .NET Standard Library Example](https://github.com/LorenData/ECGridOS_API/tree/master/ECGridOS%20API%20.NET%20Standard%20Library%20Example) that you can use for any .Net version.

In addition to using soap calls you can also make regular Sync/Async HTTP POST/GET calls to the API. Meaning you can use this API with any language and not be tied into SOAP. Included in the same examples are samples showing async HTTP POSTs that return XML and then convert that XML to JSON. The GET examples are in the [.Net 4.6 Example Project](https://github.com/LorenData/ECGridOS_API/tree/master/ECGridOS%20API%20.NET%204.6%20Examples).

In the Wiki documentation [Common API Calls](https://github.com/LorenData/ECGridOS_API/wiki/Common-API-Calls) section, are all the HTTP GET and POST requests and responses.

**Comment by jjradke** [comment]
Greg,

That is excellent news!

I don't know if you saw it or now, but in Visual Studio 2017, they now have
a WCF connector you can use to set up connections to WCF, and ASMX services
(click on Connected Services then try to add a WCF one).  I was able to use
it to create connections to all my internal webservices (all wcf or
asmx/aspx based) without any issues, and they all work seamlessly with a
.net core 2.0 application..

For some reason when I try to use it with your 3.2 url:
https://ecgridos.net/v3.2/prod/ECGridOS.asmx

it gives some errors saying that it cannot import the type wsdl:portType,
here are the errors:

=== start of errors ===

Warning: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension:
System.ServiceModel.Description.XmlSerializerMessageContractImporter
Error: Referenced type 'http://schemas.xmlsoap.org/soap/encoding/:Array' is
only valid for encoded SOAP.
XPath to Error Source: //wsdl:definitions[@targetNamespace='
http://ecgridos.net/']/wsdl:portType[@name='ECGridOS_x0020_API_x0020_v3HttpGet
']
Warning:Warning: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding
is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='
http://ecgridos.net/']/wsdl:portType[@name='ECGridOS_x0020_API_x0020_v3HttpGet
']
XPath to Error Source: //wsdl:definitions[@targetNamespace='
http://ecgridos.net/']/wsdl:binding[@name='ECGridOS_x0020_API_x0020_v3HttpGet
']
Warning:Warning: Cannot import wsdl:port
Detail:
XPath to Error Source: //wsdl:definitions[@targetNamespace='
http://ecgridos.net/']/wsdl:service[@name='ECGridOS_x0020_API_x0020_v3']/wsdl:port[@name='ECGridOS_x0020_API_x0020_v3HttpGet
']
Warning:Warning: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension:
System.ServiceModel.Description.XmlSerializerMessageContractImporter
Error: Referenced type 'http://schemas.xmlsoap.org/soap/encoding/:Array' is
only valid for encoded SOAP.
XPath to Error Source: //wsdl:definitions[@targetNamespace='
http://ecgridos.net/']/wsdl:portType[@name='ECGridOS_x0020_API_x0020_v3HttpPost
']
Warning:Warning: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding
is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='
http://ecgridos.net/']/wsdl:portType[@name='ECGridOS_x0020_API_x0020_v3HttpPost
']
XPath to Error Source: //wsdl:definitions[@targetNamespace='
http://ecgridos.net/']/wsdl:binding[@name='ECGridOS_x0020_API_x0020_v3HttpPost
']
Warning:Warning: Cannot import wsdl:port
Detail:
XPath to Error Source: //wsdl:definitions[@targetNamespace='
http://ecgridos.net/']/wsdl:service[@name='ECGridOS_x0020_API_x0020_v3']/wsdl:port[@name='ECGridOS_x0020_API_x0020_v3HttpPost
']

=== End of errors =====

Not sure what is missing from yours that causes that.  Then we wouldn't
have to worry about using the svcutil and can simply use the built in
tooling to generate the classes!

Also, are you planning on a native web api push service that could be used
for the EventCallback routines where it can push new arrivals into a
mailbox and automatically push it into our own service to receive them?  We
can use the forms based one, but a native webapi json based one would be
nice for this!

Thanks,

Jim

**Comment by GregKolinski** [comment]
Jim, 

No, I have not seen the VS2017 WCF Connector, I will have to check it out. Sorry to hear that it did not work for you. From the Errors it looks like the issues are with the HTTP GET/POST additions in the WSDL.  We will have to dig deeper into it, maybe it is something as simple as providing 2 seperate WSDLs one including the HTTP POST/GET and one for SOAP only.

Like leaving out
<wsdl:portType name="ECGridOS_x0020_API_x0020_v3Soap">...</wsdl:portType>
<wsdl:binding name="ECGridOS_x0020_API_x0020_v3Soap">...</wsdl:binding>
etc..  and removing
<wsdl:portType name="ECGridOS_x0020_API_x0020_v3HttpGet">...</wsdl:portType>
<wsdl:binding name="ECGridOS_x0020_API_x0020_v3HttpGet">...</wsdl:binding>

We are always looking for ways to improve the API, the JSON push service sounds like a great addition. We are constantly updating and improving our code base and I know that providing the data in JSON format is up there on our todo list.

Greg

**Comment by jjradke** [comment]
Greg,

The WCF Connector is available to use in apps, but you have to download it
and install it right now.  It won't be included in the base visual studio
until version 15.7 is released, which is expected in the next month or
two.  That is when they are also releasing .Net Core 2.1 - which also has
some nice features being added.

Let me know on both of these things!

I am trying to take your sample to do the ParcelDownload, and the
ParcelDownloadConfirm from the .NetCore app that I am setting up in
Docker/Kubernetes to handle the pushing of data from the CallbackEvent that
is initiated by your service when a new edi transaction arrives in our
mailboxes (replacing the IIS based ASPX app I currently have).

If I can get that working for now, I will be good for what I am working on
now!

Thanks,

Jim
