### ISSUE TITLE
Questions about ECGridOS future release

### ISSUE THREAD

**Issue by translucentapps** [LorenData/ECGridOS_API#5]
Hi. I have a few related questions related to possibility of future ECGridOS releases please...

- If this is in the works, do you have any pre-release notes?
- Will the API continue to be Soap/XML based?
- Are there plans for REST/json?

Thanks.

**Comment by GregKolinski** [comment]
Thank you for the questions.

Version 4.0 of the ECGridOS API is currently running in it's beta phase. The change log will be posted on the Revisions wiki page of this repo when it is finalized. 


At this time the API will continue to support SOAP connections, as well as HTTP Form URL Encoded requests for those not wanting to use SOAP. The return format will continue to be XML.


There has been discussions for a REST version, but it will not be in this version.

**Comment by GregKolinski** [comment]
Closing.
